apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
nodes:
- role: control-plane
  extraPortMappings:
  - containerPort: 30090
    hostPort: 30090
  - containerPort: 31448
    hostPort: 31448
  - containerPort: 31349
    hostPort: 31349
  - containerPort: 31902
    hostPort: 31902       
    listenAddress: "127.0.0.1" # Optional, defaults to "0.0.0.0"
    protocol: tcp # Optional, defaults to tcp
- role: worker